const navOpenBTN=document.querySelector(".nav-open-btn"),navCloseBTN=document.querySelector(".nav-close-btn"),mainNav=document.querySelector(".main-nav"),mainNavItems=document.querySelectorAll(".main-nav-item"),nonNavItems=document.querySelectorAll("button:not(.main-nav-item), a:not(.main-nav-item), iframe:not(.main-nav-item)");let navSizeTimeout=!1,navTabTimeout=!1;979>=window.innerWidth&&mainNavItems.forEach(b=>{b.setAttribute("tabindex",-1)});window.addEventListener("resize",navTabDebounce);
function navTabChecker(){979>=window.innerWidth?mainNavItems.forEach(b=>{b.setAttribute("tabindex",-1)}):mainNavItems.forEach(b=>{b.removeAttribute("tabindex")})}function navTabDebounce(){clearTimeout(navTabTimeout);navTabTimeout=setTimeout(navTabChecker,300)}function navSizeChecker(){980<=window.innerWidth&&closeNav()}function navSizeDebounce(){clearTimeout(navSizeTimeout);navSizeTimeout=setTimeout(navSizeChecker,300)}function mainNavControls(b){"Escape"===b.code&&closeNav()}
function openNav(){mainNav.classList.add("main-nav-open");document.body.classList.add("stop-scrolling");window.addEventListener("resize",navSizeDebounce);window.removeEventListener("resize",navTabDebounce);mainNavItems.forEach(b=>{b.removeAttribute("tabindex")});nonNavItems.forEach(b=>{b.setAttribute("tabindex",-1)});window.addEventListener("keydown",mainNavControls)}
function closeNav(){mainNav.classList.remove("main-nav-open");document.body.classList.remove("stop-scrolling");window.removeEventListener("resize",navSizeDebounce);window.addEventListener("resize",navTabDebounce);979>=window.innerWidth?mainNavItems.forEach(b=>{b.setAttribute("tabindex",-1)}):mainNavItems.forEach(b=>{b.removeAttribute("tabindex")});nonNavItems.forEach(b=>{b.removeAttribute("tabindex")});window.addEventListener("keydown",mainNavControls)}navOpenBTN.addEventListener("click",openNav);
navCloseBTN.addEventListener("click",closeNav);if(document.querySelector(".home-page")){const b=document.querySelector(".service-logo-one"),k=document.querySelector(".service-logo-two"),l=document.querySelector(".service-logo-three"),m=new IntersectionObserver(u=>{u.forEach(t=>{t.isIntersecting&&t.target.classList.add("logo-animate")})},{threshold:.5});m.observe(b);m.observe(k);m.observe(l)}
if(document.querySelector(".gallery-page")){const b=document.querySelectorAll(".gallery-image"),k=document.querySelectorAll(".gallery-image-button"),l=document.querySelector(".lightbox-container"),m=document.querySelector(".lightbox"),u=document.querySelector(".lightbox-btn-left"),t=document.querySelector(".lightbox-btn-right"),D=document.querySelector(".lightbox-btn-close"),x=document.querySelectorAll("button:not(.lightbox-nav), a:not(.lightbox-nav), iframe:not(.lightbox-nav)"),n=document.createElement("picture"),
p=document.createElement("source"),q=document.createElement("source"),r=document.createElement("source"),h=document.createElement("img");let f,y;function v(a,c,d){a=Math.ceil(a);var e=c.search("-original.");e=c.slice(0,e);const E=c.lastIndexOf("-")+1,F=c.lastIndexOf(".");c=c.slice(E,F);c=.5*Math.floor(c/a/.5);let g;4<=c?g=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@2x.webp 2x, ${e}-lightbox-${d}@3x.webp 3x, ${e}-lightbox-${d}@4x.webp 4x`:3.5===c?g=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@2x.webp 2x, ${e}-lightbox-${d}@3x.webp 3x, ${e}-lightbox-${d}@3.5x.webp 3.5x`:
3===c?g=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@2x.webp 2x, ${e}-lightbox-${d}@3x.webp 3x`:2.5===c?g=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@2x.webp 2x, ${e}-lightbox-${d}@2.5x.webp 2.5x`:2===c?g=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@2x.webp 2x`:1.5===c?g=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@1.5x.webp 1.5x`:1===c?g=`${e}-lightbox-${d}.webp 1x`:console.log("Error src density is less than 1");return g}function w(){p.setAttribute("media","(max-width: 480px)");p.setAttribute("srcset",
v(297.953,b[f].src,"small"));p.setAttribute("width",297.953);p.setAttribute("height",446.922);q.setAttribute("media","(max-width: 1024px)");q.setAttribute("srcset",v(562.984,b[f].src,"medium"));q.setAttribute("width",562.984);q.setAttribute("height",844.469);r.setAttribute("media","(min-width: 1025px)");r.setAttribute("srcset",v(600,b[f].src,"large"));r.setAttribute("width",600);r.setAttribute("height",900)}function z(){if(0!==f){f--;w();const c=b[f].src;var a=c.search("-original.");a=c.slice(0,a);
h.src=c;h.setAttribute("srcset",`${a}-lightbox-small.jpg ${298}w, ${a}-lightbox-medium.jpg ${563}w, ${a}-lightbox-large.jpg ${600}w`)}}function A(){if(f!==b.length-1){f++;w();const c=b[f].src;var a=c.search("-original.");a=c.slice(0,a);h.src=c;h.setAttribute("srcset",`${a}-lightbox-small.jpg ${298}w, ${a}-lightbox-medium.jpg ${563}w, ${a}-lightbox-large.jpg ${600}w`)}}function B(){l.classList.remove("active");document.body.classList.remove("stop-scrolling");window.removeEventListener("keydown",C);
y.focus({focusVisible:!0});x.forEach(a=>{a.removeAttribute("tabindex")});979>=window.innerWidth&&mainNavItems.forEach(a=>{a.setAttribute("tabindex",-1)})}function C(a){switch(a.code){case "Escape":B();break;case "ArrowLeft":z();break;case "ArrowRight":A()}}for(let a=0;a<b.length;a++)b[a].setAttribute("data-image-index",a),k[a].setAttribute("data-image-index",a);k.forEach(a=>{a.addEventListener("keydown",c=>{let d=Number(a.getAttribute("data-image-index"));"Enter"===c.code&&b[d].click()})});b.forEach(a=>
{a.addEventListener("click",()=>{l.classList.add("active");document.body.classList.add("stop-scrolling");f=Number(a.getAttribute("data-image-index"));w();y=k[f];m.appendChild(n);n.appendChild(p);n.appendChild(q);n.appendChild(r);const c=b[f].src;var d=c.search("-original.");d=c.slice(0,d);h.src=c;h.setAttribute("srcset",`${d}-lightbox-small.jpg ${298}w, ${d}-lightbox-medium.jpg ${563}w, ${d}-lightbox-large.jpg ${600}w`);n.appendChild(h);x.forEach(e=>{e.setAttribute("tabindex",-1)});window.addEventListener("keydown",
C)})});u.addEventListener("click",z);t.addEventListener("click",A);l.addEventListener("click",a=>{a.target!==a.currentTarget&&a.target!==D||B()})};
