const navOpenBTN=document.querySelector(".nav-open-btn"),navCloseBTN=document.querySelector(".nav-close-btn"),mainNav=document.querySelector(".main-nav"),mainNavItems=document.querySelectorAll(".main-nav-item"),nonNavItems=document.querySelectorAll("button:not(.main-nav-item), a:not(.main-nav-item), iframe:not(.main-nav-item)");let navSizeTimeout=!1,navTabTimeout=!1;979>=window.innerWidth&&mainNavItems.forEach(b=>{b.setAttribute("tabindex",-1)});window.addEventListener("resize",navTabDebounce);
function navTabChecker(){979>=window.innerWidth?mainNavItems.forEach(b=>{b.setAttribute("tabindex",-1)}):mainNavItems.forEach(b=>{b.removeAttribute("tabindex")})}function navTabDebounce(){clearTimeout(navTabTimeout);navTabTimeout=setTimeout(navTabChecker,300)}function navSizeChecker(){980<=window.innerWidth&&closeNav()}function navSizeDebounce(){clearTimeout(navSizeTimeout);navSizeTimeout=setTimeout(navSizeChecker,300)}function mainNavControls(b){"Escape"===b.code&&closeNav()}
function openNav(){mainNav.classList.add("main-nav-open");document.documentElement.classList.add("stop-scrolling");document.body.classList.add("stop-scrolling");window.addEventListener("resize",navSizeDebounce);window.removeEventListener("resize",navTabDebounce);mainNavItems.forEach(b=>{b.removeAttribute("tabindex")});nonNavItems.forEach(b=>{b.setAttribute("tabindex",-1)});window.addEventListener("keydown",mainNavControls)}
function closeNav(){mainNav.classList.remove("main-nav-open");document.documentElement.classList.remove("stop-scrolling");document.body.classList.remove("stop-scrolling");window.removeEventListener("resize",navSizeDebounce);window.addEventListener("resize",navTabDebounce);979>=window.innerWidth?mainNavItems.forEach(b=>{b.setAttribute("tabindex",-1)}):mainNavItems.forEach(b=>{b.removeAttribute("tabindex")});nonNavItems.forEach(b=>{b.removeAttribute("tabindex")});window.removeEventListener("keydown",
mainNavControls)}navOpenBTN.addEventListener("click",openNav);navCloseBTN.addEventListener("click",closeNav);if(document.querySelector(".home-page")){const b=document.querySelector(".service-logo-one"),l=document.querySelector(".service-logo-two"),k=document.querySelector(".service-logo-three"),n=new IntersectionObserver(u=>{u.forEach(m=>{m.isIntersecting&&m.target.classList.add("logo-animate")})},{threshold:.5});n.observe(b);n.observe(l);n.observe(k)}
if(document.querySelector(".gallery-page")){const b=document.querySelectorAll(".gallery-image"),l=document.querySelectorAll(".gallery-image-button"),k=document.querySelector(".lightbox-container"),n=document.querySelector(".lightbox"),u=document.querySelector(".lightbox-btn-left"),m=document.querySelector(".lightbox-btn-right"),A=document.querySelector(".lightbox-btn-close"),B=document.querySelectorAll("button:not(.lightbox-nav), a:not(.lightbox-nav), iframe:not(.lightbox-nav)"),p=document.createElement("picture"),
q=document.createElement("source"),r=document.createElement("source"),t=document.createElement("source"),g=document.createElement("img");let f,C;function v(a,c,d){a=Math.ceil(a);var e=c.search("-original.");e=c.slice(0,e);const E=c.lastIndexOf("-")+1,F=c.lastIndexOf(".");c=c.slice(E,F);c=.5*Math.floor(c/a/.5);let h;switch(!0){case 4<=c:h=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@2x.webp 2x, ${e}-lightbox-${d}@3x.webp 3x, ${e}-lightbox-${d}@4x.webp 4x`;break;case 3.5===c:h=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@2x.webp 2x, ${e}-lightbox-${d}@3x.webp 3x, ${e}-lightbox-${d}@3.5x.webp 3.5x`;
break;case 3===c:h=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@2x.webp 2x, ${e}-lightbox-${d}@3x.webp 3x`;break;case 2.5===c:h=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@2x.webp 2x, ${e}-lightbox-${d}@2.5x.webp 2.5x`;break;case 2===c:h=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@2x.webp 2x`;break;case 1.5===c:h=`${e}-lightbox-${d}.webp 1x, ${e}-lightbox-${d}@1.5x.webp 1.5x`;break;case 1===c:h=`${e}-lightbox-${d}.webp 1x`;break;default:console.log("Error src density is less than 1")}return h}
function w(){q.setAttribute("media","(max-width: 480px)");q.setAttribute("srcset",v(298,b[f].src,"small"));q.setAttribute("width",298);q.setAttribute("height",447);r.setAttribute("media","(max-width: 1024px)");r.setAttribute("srcset",v(563,b[f].src,"medium"));r.setAttribute("width",563);r.setAttribute("height",845);t.setAttribute("media","(min-width: 1025px)");t.setAttribute("srcset",v(600,b[f].src,"large"));t.setAttribute("width",600);t.setAttribute("height",900)}function x(){if(0!==f){f--;w();const c=
b[f].src;var a=c.search("-original.");a=c.slice(0,a);g.src=c;g.setAttribute("alt",b[f].alt);g.setAttribute("srcset",`${a}-lightbox-small.jpg ${298}w, ${a}-lightbox-medium.jpg ${563}w, ${a}-lightbox-large.jpg ${600}w`)}}function y(){if(f!==b.length-1){f++;w();const c=b[f].src;var a=c.search("-original.");a=c.slice(0,a);g.src=c;g.setAttribute("alt",b[f].alt);g.setAttribute("srcset",`${a}-lightbox-small.jpg ${298}w, ${a}-lightbox-medium.jpg ${563}w, ${a}-lightbox-large.jpg ${600}w`)}}function z(){u.addEventListener("click",
x);m.addEventListener("click",y);k.addEventListener("click",a=>{a.target!==a.currentTarget&&a.target!==A||z()});k.classList.remove("active");document.documentElement.classList.remove("stop-scrolling");document.body.classList.remove("stop-scrolling");window.removeEventListener("keydown",D);C.focus({focusVisible:!0});B.forEach(a=>{a.removeAttribute("tabindex")});979>=window.innerWidth&&mainNavItems.forEach(a=>{a.setAttribute("tabindex",-1)})}function D(a){switch(a.code){case "Escape":z();break;case "ArrowLeft":x();
break;case "ArrowRight":y()}}for(let a=0;a<b.length;a++)b[a].setAttribute("data-image-index",a),l[a].setAttribute("data-image-index",a);l.forEach(a=>{a.addEventListener("keydown",c=>{let d=Number(a.getAttribute("data-image-index"));"Enter"===c.code&&b[d].click()})});b.forEach(a=>{a.addEventListener("click",()=>{u.addEventListener("click",x);m.addEventListener("click",y);k.addEventListener("click",e=>{e.target!==e.currentTarget&&e.target!==A||z()});k.classList.add("active");document.documentElement.classList.add("stop-scrolling");
document.body.classList.add("stop-scrolling");f=Number(a.getAttribute("data-image-index"));w();C=l[f];n.appendChild(p);p.appendChild(q);p.appendChild(r);p.appendChild(t);const c=b[f].src;var d=c.search("-original.");d=c.slice(0,d);g.src=c;g.setAttribute("alt",b[f].alt);g.setAttribute("srcset",`${d}-lightbox-small.jpg ${298}w, ${d}-lightbox-medium.jpg ${563}w, ${d}-lightbox-large.jpg ${600}w`);p.appendChild(g);B.forEach(e=>{e.setAttribute("tabindex",-1)});window.addEventListener("keydown",D)})})};
